// GEM
export const LOAD_GEM_SUCCESS = 'LOAD_GEM_SUCCESS';
export const ADD_GEM = 'ADD_GEM';


// USER PREFERENCES
export const LOAD_USER = 'LOAD_USER';
export const DISPLAY_LIST_WITH_IMAGE = 'DISPLAY_LIST_WITH_IMAGE';
export const DISPLAY_LIST_WITHOUT_IMAGE = 'DISPLAY_LIST_WITHOUT_IMAGE';
