// GEM
export const LOAD_GEM_SUCCESS = 'LOAD_GEM_SUCCESS';
export const ADD_GEM = 'ADD_GEM';
export const DELETE_GEM = 'DELETE_GEM';

// SAVED GEM
export const LOAD_SAVED_GEM_SUCCESS = 'LOAD_SAVED_GEM_SUCCESS';
export const ADD_SAVED_GEM = 'ADD_SAVED_GEM';
export const DELETE_SAVED_GEM = 'DELETE_SAVED_GEM';

// USER PREFERENCES
export const LOAD_USER = 'LOAD_USER';
export const DISPLAY_LIST_WITH_IMAGE = 'DISPLAY_LIST_WITH_IMAGE';
export const DISPLAY_LIST_WITHOUT_IMAGE = 'DISPLAY_LIST_WITHOUT_IMAGE';
export const CATEGORY_FILTER = 'CATEGORY_FILTER';

// FRIENDS
export const LOAD_FRIENDS = 'LOAD_FRIENDS';
